// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

const pool = new Pool({
  connectionString: "postgresql://postgres:050422@localhost:5432/mini_shopee",
});

export default defineConfig({
  datasource: {
    adapter: new PrismaPg(pool),
  },
});





